"""campos_historia_clinica_y_fenotipo

Revision ID: 1cab34d8727e
Revises: e03e74d43e0d
Create Date: 2026-04-06 23:21:02.999278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cab34d8727e'
down_revision: Union[str, Sequence[str], None] = 'e03e74d43e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animales', sa.Column('sexo', sa.String(length=20), nullable=True))
    op.add_column('animales', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('animales', sa.Column('tipo_pelo', sa.String(length=50), nullable=True))
    op.add_column('animales', sa.Column('senas_particulares', sa.Text(), nullable=True))
    op.add_column('animales', sa.Column('microchip', sa.String(length=50), nullable=True))
    op.add_column('historias_clinicas', sa.Column('dieta', sa.String(length=150), nullable=True))
    op.add_column('historias_clinicas', sa.Column('enfermedades_previas', sa.Text(), nullable=True))
    op.add_column('historias_clinicas', sa.Column('cirugias_previas', sa.Text(), nullable=True))
    op.add_column('historias_clinicas', sa.Column('esterilizado', sa.String(length=2), nullable=True))
    op.add_column('historias_clinicas', sa.Column('numero_partos', sa.Integer(), nullable=True))
    op.add_column('historias_clinicas', sa.Column('esquema_vacunal', sa.Text(), nullable=True))
    op.add_column('historias_clinicas', sa.Column('ultima_desparasitacion', sa.String(length=100), nullable=True))
    op.add_column('historias_clinicas', sa.Column('tratamientos_recientes', sa.Text(), nullable=True))
    op.add_column('historias_clinicas', sa.Column('viajes_recientes', sa.String(length=100), nullable=True))
    op.add_column('historias_clinicas', sa.Column('convive_con_animales', sa.String(length=150), nullable=True))
    op.add_column('historias_clinicas', sa.Column('comportamiento', sa.String(length=100), nullable=True))
    op.add_column('historias_clinicas', sa.Column('condicion_corporal', sa.String(length=20), nullable=True))
    op.add_column('historias_clinicas', sa.Column('tllc', sa.String(length=20), nullable=True))
    op.add_column('historias_clinicas', sa.Column('trpc', sa.String(length=20), nullable=True))
    op.add_column('historias_clinicas', sa.Column('mucosas', sa.String(length=50), nullable=True))
    op.add_column('historias_clinicas', sa.Column('pulso', sa.String(length=50), nullable=True))
    op.add_column('historias_clinicas', sa.Column('deshidratacion', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historias_clinicas', 'deshidratacion')
    op.drop_column('historias_clinicas', 'pulso')
    op.drop_column('historias_clinicas', 'mucosas')
    op.drop_column('historias_clinicas', 'trpc')
    op.drop_column('historias_clinicas', 'tllc')
    op.drop_column('historias_clinicas', 'condicion_corporal')
    op.drop_column('historias_clinicas', 'comportamiento')
    op.drop_column('historias_clinicas', 'convive_con_animales')
    op.drop_column('historias_clinicas', 'viajes_recientes')
    op.drop_column('historias_clinicas', 'tratamientos_recientes')
    op.drop_column('historias_clinicas', 'ultima_desparasitacion')
    op.drop_column('historias_clinicas', 'esquema_vacunal')
    op.drop_column('historias_clinicas', 'numero_partos')
    op.drop_column('historias_clinicas', 'esterilizado')
    op.drop_column('historias_clinicas', 'cirugias_previas')
    op.drop_column('historias_clinicas', 'enfermedades_previas')
    op.drop_column('historias_clinicas', 'dieta')
    op.drop_column('animales', 'microchip')
    op.drop_column('animales', 'senas_particulares')
    op.drop_column('animales', 'tipo_pelo')
    op.drop_column('animales', 'color')
    op.drop_column('animales', 'sexo')
    # ### end Alembic commands ###
