"""sincronizando_campos_nuevos

Revision ID: 38d0897cfe7e
Revises: ab36d21bb9e4
Create Date: 2026-04-07 11:10:00.566046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d0897cfe7e'
down_revision: Union[str, Sequence[str], None] = 'ab36d21bb9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
