"""agregada_unidad_edad_y_nacimiento

Revision ID: ab36d21bb9e4
Revises: 1cab34d8727e
Create Date: 2026-04-06 23:26:30.008660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab36d21bb9e4'
down_revision: Union[str, Sequence[str], None] = '1cab34d8727e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animales', sa.Column('unidad_edad', sa.String(length=20), nullable=True))
    op.add_column('animales', sa.Column('fecha_nacimiento', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animales', 'fecha_nacimiento')
    op.drop_column('animales', 'unidad_edad')
    # ### end Alembic commands ###
