"""agregados_datos_propietario_y_empresa

Revision ID: e03e74d43e0d
Revises: 5688c877a6a6
Create Date: 2026-04-06 22:52:35.287316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03e74d43e0d'
down_revision: Union[str, Sequence[str], None] = '5688c877a6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=True),
    sa.Column('raza', sa.String(length=50), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('propietario', sa.String(length=150), nullable=True),
    sa.Column('propietario_tipo_doc', sa.String(length=20), nullable=True),
    sa.Column('propietario_documento', sa.String(length=50), nullable=True),
    sa.Column('propietario_direccion', sa.String(length=150), nullable=True),
    sa.Column('propietario_oficio', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fecha_ingreso', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animales_codigo'), 'animales', ['codigo'], unique=True)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_hora', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muestras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('tipo_muestra', sa.String(length=50), nullable=False),
    sa.Column('tipo_analisis', sa.String(length=100), nullable=True),
    sa.Column('fecha_recoleccion', sa.String(length=20), nullable=False),
    sa.Column('fecha_entrega', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('valor_referencia', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('tecnico', sa.String(length=100), nullable=True),
    sa.Column('veterinario_ref', sa.String(length=100), nullable=True),
    sa.Column('urgente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('recepciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.String(length=50), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('veterinario', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('proxima_cita', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('vacunaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('dosis', sa.String(length=50), nullable=True),
    sa.Column('via', sa.String(length=50), nullable=True),
    sa.Column('fecha_aplicacion', sa.String(length=20), nullable=False),
    sa.Column('fecha_proxima', sa.String(length=20), nullable=True),
    sa.Column('veterinario', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('historias_clinicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('anamnesis', sa.Text(), nullable=True),
    sa.Column('examen_fisico', sa.Text(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('peso_consulta', sa.Float(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('diagnostico_diferencial', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('pronostico', sa.Text(), nullable=True),
    sa.Column('veterinario', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cirugias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('tipo_cirugia', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('anestesia', sa.String(length=50), nullable=True),
    sa.Column('protocolo_anestesico', sa.Text(), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('cirujano', sa.String(length=100), nullable=True),
    sa.Column('anestesiologo', sa.String(length=100), nullable=True),
    sa.Column('asistente', sa.String(length=100), nullable=True),
    sa.Column('complicaciones', sa.Text(), nullable=True),
    sa.Column('cuidados_post', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('evolucion', sa.Text(), nullable=True),
    sa.Column('examen_fisico', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('medicamentos', sa.Text(), nullable=True),
    sa.Column('proxima_consulta', sa.String(length=20), nullable=True),
    sa.Column('veterinario', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['historia_id'], ['historias_clinicas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    op.drop_table('cirugias')
    op.drop_table('historias_clinicas')
    op.drop_table('vacunaciones')
    op.drop_table('recepciones')
    op.drop_table('muestras')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_animales_codigo'), table_name='animales')
    op.drop_table('animales')
    # ### end Alembic commands ###
